# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversationtree', '0003_conversationtree_rootnode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationnode',
            name='name',
        ),
        migrations.AddField(
            model_name='conversationnode',
            name='intent',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='conversationnode',
            name='parentNode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='conversationtree.ConversationNode'),
        ),
        migrations.AlterField(
            model_name='conversationnode',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='conversationtree',
            name='rootNode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='conversationtree.ConversationNode'),
        ),
        migrations.AlterField(
            model_name='conversationtree',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
