# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversationtree', '0004_auto_20171019_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationnode',
            name='message',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
