# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversationtree', '0005_conversationnode_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationnode',
            name='intent',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
