# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-22 22:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('conversationtree', '0008_auto_20171022_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
