# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('conversationtree', '0009_auto_20171023_0148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('template', models.CharField(max_length=500)),
                ('node', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversationtree.Node')),
            ],
        ),
    ]
