# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversationtree', '0009_auto_20171023_0148'),
        ('conversationtree', '0009_telegramuser'),
    ]

    operations = [
    ]
