# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversationtree', '0010_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
