# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-23 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('conversationtree', '0010_auto_20171023_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
