# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-25 21:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversationtree', '0012_auto_20171023_1810'),
        ('conversationtree', '0012_template'),
    ]

    operations = [
    ]
