# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 07:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversationtree', '0019_auto_20171116_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('value', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='conversationtree.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversationtree.TelegramUser')),
            ],
        ),
    ]
