# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-05 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversationtree', '0020_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='is_trained',
            field=models.BooleanField(default=False),
        ),
    ]
