# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-06 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversationtree', '0021_template_is_trained'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
