# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-16 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversationtree', '0022_auto_20171206_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='avg_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='count',
            field=models.IntegerField(null=True),
        ),
    ]
