# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-16 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversationtree', '0023_auto_20171216_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='avg_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
