# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20170424_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('surname', models.CharField(blank=True, default='', max_length=50)),
                ('age', models.CharField(choices=[('english', 'english'), ('turkish', 'turkish')], default='', max_length=50)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
